---

name: module3_task1

"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: ./module3_task1/*.md
          config_file: .markdownlint.yaml
          dot: true
          ignore_files: ./module3_task1/themes/*
          ignore_path: ./module3_task1/themes/

      - name: html5validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0  
        with:
          root: /opt/

      - name: Install Dependancies
        uses: golangci/golangci-lint-action@v3

      - name: Build Workflow
        run: cd module3_task1 && make build
