---

name: module3_task1

"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Dependancies
        uses: golangci/golangci-lint-action@v3

      - name: Build Workflow
        run: cd module3_task1 && make build
