---

name: module3_task0
"on": 
  push:
  schedule:
    - cron: "5 6 * * *"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Package
        run: apt-get go hugo make -yq
      - name: Build
        run: make build

---
