---

name: module3_task0
"on":
  schedule:
    - cron: '3 * * *'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Actions
        uses:
          actions/checkout@v2

      - name: Install Package
        run:
          apt-get go hugo make -yq

      - name: Run Project
        run:
          make build

---
