---

name: module3_task1

"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'


jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Workflow
        run: cd module3_task1 && ./setup.sh && make build
